version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: someReallySecurePassword
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: naturalh
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"  # Exposing MySQL port
    volumes:
      - mysql_data:/var/lib/mysql  # Persist data locally
    networks:
      - app_network

volumes:
  mysql_data:
    driver: local  # Use a local volume for persistence

networks:
  app_network:
    driver: bridge

